In [150]:
import numpy as np
import pandas as pd
import pandasql as psql

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [31]:
df = pd.read_csv("~/Downloads/bigml_59c28831336c6604c800002a.csv")

In [137]:
df.describe()

state  account length    area code  phone number  \
count  3333.000000     3333.000000  3333.000000  3.333000e+03   
mean     26.059406      101.064806   437.182418  3.746291e+06   
std      14.824911       39.822106    42.371290  2.746626e+05   
min       0.000000        1.000000   408.000000  3.271058e+06   
25%      14.000000       74.000000   408.000000  3.508680e+06   
50%      26.000000      101.000000   415.000000  3.748187e+06   
75%      39.000000      127.000000   510.000000  3.985970e+06   
max      50.000000      243.000000   510.000000  4.229964e+06   

       international plan  voice mail plan  number vmail messages  \
count         3333.000000      3333.000000            3333.000000   
mean             0.096910         0.276628               8.099010   
std              0.295879         0.447398              13.688365   
min              0.000000         0.000000               0.000000   
25%              0.000000         0.000000               0.000000   
50%              0.000000         0.000000               0.000000   
75%              0.000000         1.000000              20.000000   
max              1.000000         1.000000              51.000000   

       total day minutes  total day calls  total day charge  \
count        3333.000000      3333.000000       3333.000000   
mean          179.775098       100.435644         30.562307   
std            54.467389        20.069084          9.259435   
min             0.000000         0.000000          0.000000   
25%           143.700000        87.000000         24.430000   
50%           179.400000       101.000000         30.500000   
75%           216.400000       114.000000         36.790000   
max           350.800000       165.000000         59.640000   

       total eve minutes  total eve calls  total eve charge  \
count        3333.000000      3333.000000       3333.000000   
mean          200.980348       100.114311         17.083540   
std            50.713844        19.922625          4.310668   
min             0.000000         0.000000          0.000000   
25%           166.600000        87.000000         14.160000   
50%           201.400000       100.000000         17.120000   
75%           235.300000       114.000000         20.000000   
max           363.700000       170.000000         30.910000   

       total night minutes  total night calls  total night charge  \
count          3333.000000        3333.000000         3333.000000   
mean            200.872037         100.107711            9.039325   
std              50.573847          19.568609            2.275873   
min              23.200000          33.000000            1.040000   
25%             167.000000          87.000000            7.520000   
50%             201.200000         100.000000            9.050000   
75%             235.300000         113.000000           10.590000   
max             395.000000         175.000000           17.770000   

       total intl minutes  total intl calls  total intl charge  \
count         3333.000000       3333.000000        3333.000000   
mean            10.237294          4.479448           2.764581   
std              2.791840          2.461214           0.753773   
min              0.000000          0.000000           0.000000   
25%              8.500000          3.000000           2.300000   
50%             10.300000          4.000000           2.780000   
75%             12.100000          6.000000           3.270000   
max             20.000000         20.000000           5.400000   

       customer service calls  
count             3333.000000  
mean                 1.562856  
std                  1.315491  
min                  0.000000  
25%                  1.000000  
50%                  1.000000  
75%                  2.000000  
max                  9.000000

In [56]:
df.dtypes

state                      object
account length              int64
area code                   int64
phone number                int64
international plan         object
voice mail plan            object
number vmail messages       int64
total day minutes         float64
total day calls             int64
total day charge          float64
total eve minutes         float64
total eve calls             int64
total eve charge          float64
total night minutes       float64
total night calls           int64
total night charge        float64
total intl minutes        float64
total intl calls            int64
total intl charge         float64
customer service calls      int64
churn                        bool
dtype: object

In [168]:
q1 = ("""
SELECT *,
CASE 
    WHEN "total intl calls" > 0 THEN 1
    ELSE 0 
END AS intlcalls,
CASE 
    WHEN "total eve calls" > 0 THEN 1
    ELSE 0 
END AS evecalls,
CASE 
    WHEN "total night calls" > 0 THEN 1
    ELSE 0
END AS nightcalls,
CASE
    WHEN "total day calls" > 0 THEN 1
    ELSE 0
END AS daycalls,
CASE
    WHEN "customer service calls" > 1 THEN 1 
    ELSE 0
END AS customerservice
FROM df
""")
df1 = psql.sqldf(q1)
df1 = df1.drop(columns = ['total intl calls','total eve calls','total night calls','total day calls','customer service calls'])

In [183]:
q2 = """
SELECT "state", "account length", "area code", "phone number",
"international plan", "voice mail plan", "number vmail messages",
"total day minutes", "total day calls", "total day charge",
"total eve minutes", "total eve calls", "total eve charge",
"total night minutes", "total night calls", "total night charge",
"total intl minutes", "total intl calls", "total intl charge",
"customer service calls", "churn"
FROM df
LIMIT 5
"""
psql.sqldf(q2)

state  account length  area code  phone number  international plan  \
0     16             128        415       3824657                   0   
1     35             107        415       3717191                   0   
2     31             137        415       3581921                   0   
3     35              84        408       3759999                   1   
4     36              75        415       3306626                   1   

   voice mail plan  number vmail messages  total day minutes  total day calls  \
0                1                     25              265.1              110   
1                1                     26              161.6              123   
2                0                      0              243.4              114   
3                0                      0              299.4               71   
4                0                      0              166.7              113   

   total day charge  ...  total eve calls  total eve charge  \
0             45.07  ...               99             16.78   
1             27.47  ...              103             16.62   
2             41.38  ...              110             10.30   
3             50.90  ...               88              5.26   
4             28.34  ...              122             12.61   

   total night minutes  total night calls  total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   total intl minutes  total intl calls  total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   customer service calls  churn  
0                       1      0  
1                       1      0  
2                       0      0  
3                       2      0  
4                       3      0  

[5 rows x 21 columns]

In [ ]:
# actually we dont really need the column phone number because it will cause over fitting and will not have a 
# correlation between our train and test data.

In [74]:
le = LabelEncoder()
df['state'] = le.fit_transform(df['state'])
df['international plan'] = le.fit_transform(df['international plan'])
df['voice mail plan'] = le.fit_transform(df['voice mail plan'])


In [152]:
X = df.drop(columns = ['churn','phone number'])
y = df['churn']
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,random_state=42)

In [147]:
dtc = DecisionTreeClassifier(max_depth=22)
dtc.fit(Xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=22,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [148]:
y_preds = dtc.predict(Xtrain)

In [149]:
confusion_matrix(ytrain,y_preds)

array([[2141,    0],
       [   0,  358]])

In [170]:
X1 = df1.drop(columns = ['churn','phone number'])
y1 = df1['churn']
Xtrain1,Xtest1,ytrain1,ytest1 = train_test_split(X1,y1,random_state=42)

In [156]:
rfc = RandomForestClassifier(n_estimators=100,random_state=42)

In [157]:
rfc.fit(Xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [158]:
y_predsrfc = rfc.predict(Xtrain)

In [159]:
confusion_matrix(ytrain,y_predsrfc)

array([[2141,    0],
       [   0,  358]])

In [160]:
rfc.feature_importances_

array([0.02472057, 0.02867274, 0.00857789, 0.08677414, 0.02023758,
       0.02702115, 0.13428955, 0.03074894, 0.13058729, 0.06298392,
       0.02874081, 0.06677738, 0.03676844, 0.03198688, 0.03508086,
       0.04161329, 0.0448703 , 0.03693667, 0.1226116 ])

In [174]:
rfc.fit(Xtrain,ytrain)
y_predsrfc1 = rfc.predict(Xtest)
confusion_matrix(ytest,y_predsrfc1)

array([[706,   3],
       [ 40,  85]])

In [172]:
rfc.feature_importances_

array([4.91070803e-02, 6.06526673e-02, 1.65588081e-02, 7.48397388e-02,
       2.03644602e-02, 3.51540636e-02, 1.42441263e-01, 1.43128142e-01,
       9.48169187e-02, 9.09905788e-02, 6.81493823e-02, 6.54831593e-02,
       6.49352200e-02, 6.62735176e-02, 1.21821114e-04, 6.08351449e-08,
       0.00000000e+00, 0.00000000e+00, 6.98311852e-03])

In [173]:
y_final = rfc.predict(Xtest1)
confusion_matrix(ytest1,y_final)

array([[705,   4],
       [ 71,  54]])